### PR TITLE
(feat): Add metrics.cfg.xml support to ele-repose (v8+)

### PR DESCRIPTION
**Pull request by dimtruck**
fixed https://github.com/mmi-cookbooks/ele-repose/issues/56

Added metrics configuration support to ele-repose

### CODE REVIEW

**Comment by dimtruck** [comment]
Hmmm, we do utilize ele attributes in this cookbook already: https://github.com/dimtruck/ele-repose/blob/6ac4a11d5688f7e5ef411b47a239a4cad31d787e/recipes/default.rb#L79-L87

**Comment by dimtruck** [comment]
As is, it needs https://github.com/racker/chef/pull/4028 to stage attributes.  If we decide not to duplicate (and do a dependency or something else), that PR won't be necessary.

**Comment by dimtruck** [comment]
cc/ @shawnashlee @drenalin23

**Comment by mburns** [comment]
rebase should fix (some) of the CI errors that are currently failing.

**Comment by shawnashlee** [comment]
lgtm

**Pull request closed without merging**
