### PR TITLE
Remove prefix from metrics

### PR DESCRIPTION
**Pull request by dimtruck**
Right now we're prepending a hostname to repose metrics.  That's redundant because repose does the same thing internally!  

This pr removes it from default attributes.

**Do not merge.  This is a PR that is a patch to 0.3.17**

### CODE REVIEW

**Comment by mburns** [comment]
LGTM 👍 

CI errors are because of ruby version used, fixed in #71:

```
Gem::InstallError: buff-ignore requires Ruby version >= 2.1.
```

**Comment by jjbuchan** [comment]
retest this please ?

**Comment by jjbuchan** [comment]
+1

**Comment by mburns** [comment]
closing for now. Branch still exists. Can update and merge when ready. /CC @dimtruck

**Pull request closed without merging**
